### ISSUE TITLE
shouldComponentUpdate issue

### ISSUE THREAD

**Issue by rt2zz** [gnoff/react-tunnel#2]
My injected component was not rerendering. I believe based on cursory review that inject should be using `shallowEqualScalar` on both provided and props (instead of shallow equal on just provided)

**Comment by gnoff** [comment]
updated to shallowEqual compare props. also changed provided compare to use nextState rather than nextContext since this is the mapped version of provided.

69e7270477d1d685f272bdb594f6502a07a52058

closing
